export const listings = [
  {
    id: 1,
    image: "/assets/images/chatgpt.png",
    title: "CHATGPT",
    link: "https://chat.openai.com",
    description: "An ask-it-all AI chatbot",
  },
  {
    id: 2,
    image: "/assets/images/dall-e.png",
    title: "DALL-E",
    link: "https://labs.openai.com",
    description: "Image Generator",
  },
  {
    id: 3,
    image: "/assets/images/gfpgan.png",
    title: "GFPGAN",
    link: "https://huggingface.co/spaces/Xintao/GFPGAN",
    description: "Image restoration tool",
  },
  {
    id: 4,
    image: "/assets/images/brandmark.png",
    title: "BRANDMARK",
    link: "https://brandmark.io",
    description: "Generate brandnames",
  },
  {
    id: 5,
    image: "/assets/images/lumen5.png",
    title: "LUMEN5",
    link: "https://lumen5.com/blog-to-video",
    description: "Video generator",
  },
  {
    id: 6,
    image: "/assets/images/talk-to-books.png",
    title: "TALK-TO-BOOKS",
    link: "https://books.google.com/talktobooks",
    description: "Interact with books",
  },
  {
    id: 7,
    image: "/assets/images/deepbeat.png",
    title: "DEEPBEAT",
    link: "https://deepbeat.org",
    description: "Rap lyrics generator",
  },
  {
    id: 8,
    image: "/assets/images/riffusion.png",
    title: "RIFFUSION",
    link: "https://www.riffusion.com",
    description: "Beat generator",
  },
  {
    id: 9,
    image: "/assets/images/magic-eraser.png",
    title: "MAGIC-ERASER",
    link: "https://magicstudio.com/magiceraser",
    description: "Object remover",
  },
  {
    id: 10,
    image: "/assets/images/midjourney.png",
    title: "MIDJOURNEY",
    link: "https://www.midjourney.com/home/?callbackUrl=%2Fapp%2F",
    description: "To create fascinating art",
  },
  {
    id: 11,
    image: "/assets/images/forms-app.png",
    title: "FORMS-APP",
    link: "https://forms.app/en/ai-form-generator",
    description: "To create forms,surveys and quizzes",
  },
  {
    id: 12,
    image: "/assets/images/notion.png",
    title: "NOTION",
    link: "https://www.notion.so",
    description: "create to-do lists, add notes",
  },
  {
    id: 13,
    image: "/assets/images/flickr.png",
    title: "FLICKR",
    link: "https://www.flickr.com",
    description: "Finding caption for social media",
  },
  {
    id: 14,
    image: "/assets/images/fontjoy.png",
    title: "FONTJOY",
    link: "https://fontjoy.com",
    description: "To create font combination",
  },
  {
    id: 15,
    image: "/assets/images/fireflies.png",
    title: "FIREFLIES",
    link: "https://fireflies.ai",
    description: "To generate notes from meetings",
  },
  {
    id: 16,
    image: "/assets/images/fireflies.png",
    title: "GETMunch",
    link: "https://www.getmunch.com",
    description: "Content Repourposing done smart",
    type: "freemium",
    catagory: "video generation",
  },
  {
    id: 17,
    image: "/assets/images/fireflies.png",
    title: "WEBMAGIC",
    link: "https://www.magicapps.ai/webmagic-ai",
    description: "Article summarizer",
    type: "freemium",
    catagory: "productivity",
  },
  {
    id: 18,
    image: "/assets/images/fireflies.png",
    title: "ADCREATIVE",
    link: "https://www.adcreative.ai/",
    description: "Generate ad creatives and social media post",
    type: "paid",
    category: "sales",
  },
  {
    id: 19,
    image: "/assets/images/fireflies.png",
    title: "POSTWISE",
    link: "https://postwise.ai",
    description: "Write AI Tweets",
    type: "paid",
    category: "social-media-assistant",
  },
  {
    id: 20,
    image: "/assets/images/fireflies.png",
    title: "B12",
    link: "https://www.b12.io",
    description: "Website Builder",
    type: "paid",
    category: "e-commerce",
  },
  {
    id: 21,
    image: "/assets/images/fireflies.png",
    title: "LEARNATIVE",
    link: "https://www.learnitive.com/",
    description: "Acadamic Writer",
    type: "freemium",
    category: "education",
  },
];
