export const listings=[
    {
        "id":1,
        "image":"/assets/images/chatgpt.png",
        "title":"CHATGPT"
    },
    {
        "id":2,
        "image":"/assets/images/dall-e.png",
        "title":"CHATGPT"
    },
    {
        "id":3,
        "image":"/assets/images/gfpgan.png",
        "title":"CHATGPT"
    },
    {
        "id":4,
        "image":"/assets/images/brandmark.png",
        "title":"CHATGPT"
    },
    {
        "id":5,
        "image":"/assets/images/lumen5.png",
        "title":"CHATGPT"
    },
    {
        "id":6,
        "image":"/assets/images/talk-to-books.png",
        "title":"CHATGPT"
    },
    {
        "id":7,
        "image":"/assets/images/deepbeat.png",
        "title":"CHATGPT"
    },
    {
        "id":8,
        "image":"/assets/images/fireflies.png",
        "title":"CHATGPT"
    },
    {
        "id":9,
        "image":"/assets/images/magic-eraser.png",
        "title":"CHATGPT"
    },
    {
        "id":10,
        "image":"/assets/images/fontjoy.png",
        "title":"CHATGPT"
    },
    {
        "id":11,
        "image":"/assets/images/forms-app.png",
        "title":"CHATGPT"
    },
    {
        "id":12,
        "image":"/assets/images/notion.png",
        "title":""
    },
    {
        "id":13,
        "image":"/assets/images/flickr.png",
        "title":""
    },
    {
        "id":14,
        "image":"/assets/images/midjourney.png",
        "title":""
    },
    {
        "id":15,
        "image":"/assets/images/riffusion.png",
        "title":""
    },
]
