export const listings = [
  {
    id: 1,
    image: "/assets/images/chatgpt.png",
    title: "CHATGPT",
    link: "https://chat.openai.com",
    description: "An ask-it-all AI chatbot",
  },
  {
    id: 2,
    image: "/assets/images/dall-e.png",
    title: "DALL-E",
    link: "https://labs.openai.com",
    description: "Image Generator",
  },
  {
    id: 3,
    image: "/assets/images/gfpgan.png",
    title: "GFPGAN",
    link: "https://huggingface.co/spaces/Xintao/GFPGAN",
    description: "Image restoration tool",
  },
  {
    id: 4,
    image: "/assets/images/brandmark.png",
    title: "BRANDMARK",
    link: "https://brandmark.io",
    description: "Generate brandnames",
  },
  {
    id: 5,
    image: "/assets/images/lumen5.png",
    title: "LUMEN5",
    link: "https://lumen5.com/blog-to-video",
    description: "Video generator",
  },
  {
    id: 6,
    image: "/assets/images/talk-to-books.png",
    title: "TALK-TO-BOOKS",
    link: "https://books.google.com/talktobooks",
    description: "Interact with books",
  },
  {
    id: 7,
    image: "/assets/images/deepbeat.png",
    title: "DEEPBEAT",
    link: "https://deepbeat.org",
    description: "Rap lyrics generator",
  },
  {
    id: 8,
    image: "/assets/images/riffusion.png",
    title: "RIFFUSION",
    link: "https://www.riffusion.com",
    description: "Beat generator",
  },
  {
    id: 9,
    image: "/assets/images/magic-eraser.png",
    title: "MAGIC-ERASER",
    link: "https://magicstudio.com/magiceraser",
    description: "Object remover",
  },
  {
    id: 10,
    image: "/assets/images/midjourney.png",
    title: "MIDJOURNEY",
    link: "https://www.midjourney.com/home/?callbackUrl=%2Fapp%2F",
    description: "To create fascinating art",
  },
  {
    id: 11,
    image: "/assets/images/forms-app.png",
    title: "FORMS-APP",
    link: "https://forms.app/en/ai-form-generator",
    description: "To create forms,surveys and quizzes",
  },
  {
    id: 12,
    image: "/assets/images/notion.png",
    title: "NOTION",
    link: "https://www.notion.so",
    description: "create to-do lists, add notes",
  },
  {
    id: 13,
    image: "/assets/images/flickr.png",
    title: "FLICKR",
    link: "https://www.flickr.com",
    description: "Finding caption for social media",
  },
  {
    id: 14,
    image: "/assets/images/fontjoy.png",
    title: "FONTJOY",
    link: "https://fontjoy.com",
    description: "To create font combination",
  },
  {
    id: 15,
    image: "/assets/images/fireflies.png",
    title: "FIREFLIES",
    link: "https://fireflies.ai",
    description: "To generate notes from meetings",
  },
  {
    id: 16,
    image: "/assets/images/munch.jpeg",
    title: "GETMunch",
    link: "https://www.getmunch.com",
    description: "Content Repourposing done smart",
    type: "freemium",
    catagory: "Video Generation",
  },
  {
    id: 17,
    image: "/assets/images/av-mapping.png",
    title: "A.V.MAPPING",
    link: "https://www.magicapps.ai/webmagic-ai",
    description: "AI stop shop to find the music from your video",
    type: "free",
    catagory: "Video Generation",
  },
  {
    id: 18,
    image: "/assets/images/pictory.jpg",
    title: "PICTORY AI",
    link: "https://www.adcreative.ai/",
    description: "for creating marketing videos from long-form content",
    type: "paid",
    category: "Video Generation",
  },
  {
    id: 19,
    image: "/assets/images/fliki.jpg",
    title: "FLIKI",
    link: "https://postwise.ai",
    description: "text-to-video creation using AI Voices",
    type: "freemium",
    category: "Video Generation",
  },
  {
    id: 20,
    image: "/assets/images/prodia.png",
    title: "PRODIA",
    link: "https://www.b12.io",
    description: "to help implement generative AI into your app",
    type: "free",
    category: "Image Generation",
  },
  {
    id: 21,
    image: "/assets/images/magic-studio.png",
    title: "MAGIC STUDIO",
    link: "https://www.learnitive.com/",
    description: "enables automatic image creation and editing",
    type: "free",
    category: "Image Generation",
  },
  {
    id: 22,
    image: "/assets/images/playground.png",
    title: "PLAYGROUND AI",
    link: "https://www.learnitive.com/",
    description: "AI image creator",
    type: "free",
    category: "Image Generation",
  },
  {
    id: 23,
    image: "/assets/images/frase.png",
    title: "FRASE",
    link: "https://www.learnitive.com/",
    description: "AI helps you research, write, and optimize high-quality SEO content",
    type: "free",
    category: "Content Creation",
  },
  {
    id: 24,
    image: "/assets/images/bearly.jpg",
    title: "BEARLY AI",
    link: "https://www.learnitive.com/",
    description: "AI that helps you write, read and change text with just a click",
    type: "free",
    category: "Writing Assistant",
  },
  {
    id: 25,
    image: "/assets/images/phonesites.png",
    title: "PHONESITES",
    link: "https://www.learnitive.com/",
    description: "to easily build websites, landing pages, surveys, pop-ups",
    type: "free",
    category: "Writing Assistant",
  },
  {
    id: 26,
    image: "/assets/images/yaara.jpeg",
    title: "YAARA.AI",
    link: "https://www.learnitive.com/",
    description: "creative content generator for your writing needs",
    type: "freemium",
    category: "Copywriting",
  },
  {
    id: 27,
    image: "/assets/images/copy-ai.png",
    title: "COPY.AI",
    link: "https://www.learnitive.com/",
    description: "creating more effective marketing copy and content",
    type: "freemium",
    category: "Copywriting",
  },
  {
    id: 28,
    image: "/assets/images/copy-monkey.jpeg",
    title: "COPYMONKEY",
    link: "https://www.learnitive.com/",
    description: "AI for Amazon Listing Optimization",
    type: "paid",
    category: "Copywriting",
  },
  {
    id: 29,
    image: "/assets/images/reflect.png",
    title: "REFLECT AI",
    link: "https://www.learnitive.com/",
    description: "Use OpenAI's GPT4 and write your own custom prompts",
    type: "paid",
    category: "Productivity",
  },
  {
    id: 30,
    image: "/assets/images/playht.jpeg",
    title: "PLAY HT",
    link: "https://www.learnitive.com/",
    description: "Generate realistic Text to Speech voice",
    type: "paid",
    category: "Audio Generation",
  },
  {
    id: 31,
    image: "/assets/images/musicfy.jpeg",
    title: "MUSICFY",
    link: "https://www.learnitive.com/",
    description: "create custom music covers, remixes",
    type: "free",
    category: "Audio Generation",
  },
  {
    id: 32,
    image: "/assets/images/murf.png",
    title: "MURF.AI",
    link: "https://www.learnitive.com/",
    description: "AI Voice Generator in 20 languages",
    type: "free",
    category: "Audio Generation",
  },
  {
    id: 33,
    image: "/assets/images/looka.png",
    title: "LOOKA AI",
    link: "https://www.learnitive.com/",
    description: "Design a Logo and make a website",
    type: "free",
    category: "Design",
  },
  {
    id: 34,
    image: "/assets/images/namecheap.png",
    title: "NAMECHEAP",
    link: "https://www.learnitive.com/",
    description: "free logo maker using AI",
    type: "free",
    category: "Design",
  },
  {
    id: 35,
    image: "/assets/images/autodraw.png",
    title: "AUTODRAW",
    link: "https://www.learnitive.com/",
    description: "It pairs machine learning with drawings from talented artists",
    type: "free",
    category: "Design",
  },
  {
    id: 36,
    image: "/assets/images/postwise.jpeg",
    title: "POSTWISE",
    link: "https://www.learnitive.com/",
    description: "Write tweets, schedule posts and grow your following",
    type: "paid",
    category: "Social media Assistant",
  },
  {
    id: 37,
    image: "/assets/images/tweet-hunter.png",
    title: "TWEET HUNTER",
    link: "https://www.learnitive.com/",
    description: "increase your Twitter following and achieve more",
    type: "freemium",
    category: "Social media Assistant",
  },
  {
    id: 38,
    image: "/assets/images/chatoga.png",
    title: "CHATOGA",
    link: "https://www.learnitive.com/",
    description: "Experience ChatGPT On WhatsApp & Telegram",
    type: "free",
    category: "Social media Assistant",
  },
  {
    id: 39,
    image: "/assets/images/fini.jpeg",
    title: "FINI",
    link: "https://www.learnitive.com/",
    description: " their knowledge base into an AI agent",
    type: "freemium",
    category: "Chat Bot",
  },
  {
    id: 40,
    image: "/assets/images/chatlab.jpg",
    title: "AI CHATLAB",
    link: "https://www.learnitive.com/",
    description: "  all-in-one chatbot platform",
    type: "free",
    category: "Chat Bot",
  },
  {
    id: 41,
    image: "/assets/images/chunky.jpg",
    title: "CHUNKY",
    link: "https://www.learnitive.com/",
    description: "create your own GPT-powered, specialized agents",
    type: "paid",
    category: "Chat Bot",
  },
  {
    id: 42,
    image: "/assets/images/clippah.png",
    title: "CLIPPAH",
    link: "https://www.learnitive.com/",
    description: "Easily convert YouTube videos to vertical TikToks",
    type: "free",
    category: "Video Editing",
  },
  {
    id: 43,
    image: "/assets/images/riverside.jpg",
    title: "RIVERSIDE",
    link: "https://www.learnitive.com/",
    description: "Professional podcast and video creation",
    type: "freemium",
    category: "Video Editing",
  },
  {
    id: 44,
    image: "/assets/images/vizard.jpeg",
    title: "VIZARD.AI",
    link: "https://www.learnitive.com/",
    description: "video editing tool designed for content marketers",
    type: "free",
    category: "Video Editing",
  },
  {
    id: 45,
    image: "/assets/images/browse.png",
    title: "BROWSE AI",
    link: "https://www.learnitive.com/",
    description: "Monitor any webpage for changes",
    type: "freemium",
    category: "Research",
  },
  {
    id: 46,
    image: "/assets/images/upword.png",
    title: "UPWORD",
    link: "https://www.learnitive.com/",
    description: "AI-powered research tool for individuals and teams",
    type: "freemium",
    category: "Research",
  },
  {
    id: 47,
    image: "/assets/images/sourcely.jpg",
    title: "SOURCELY",
    link: "https://www.learnitive.com/",
    description: "automated literature sourcing service",
    type: "freemium",
    category: "Research",
  },
  {
    id: 48,
    image: "/assets/images/replit.png",
    title: "REPLIT",
    link: "https://www.learnitive.com/",
    description: "AI code assistant that helps you write better code faster",
    type: "freemium",
    category: "Code Assistant",
  },
  {
    id: 49,
    image: "/assets/images/kodezi.jpg",
    title: "KODEZI",
    link: "https://www.learnitive.com/",
    description: " auto-corrects your code!",
    type: "freemium",
    category: "Code Assistant",
  },
  {
    id: 50,
    image: "/assets/images/codium.png",
    title: "CODIUM AI",
    link: "https://www.learnitive.com/",
    description: "supports Python,Java, and can tackle complicated code",
    type: "free",
    category: "Code Assistant",
  },
  {
    id: 51,
    image: "/assets/images/talkpal.png",
    title: "TALKPAL AI",
    link: "https://www.learnitive.com/",
    description: "TalkPal is a GPT-powered AI language tutor",
    type: "freemium",
    category: "Education",
  },
  {
    id: 52,
    image: "/assets/images/learnitive.jpg",
    title: "LEARNITIVE",
    link: "https://www.learnitive.com/",
    description: "all-in-one AI-enabled academic platform",
    type: "freemium",
    category: "Education",
  },
  {
    id: 53,
    image: "/assets/images/airops.jpeg",
    title: "AIROPS",
    link: "https://www.learnitive.com/",
    description: "collection of powerful AI apps ",
    type: "freemium",
    category: "All In One",
  },
  {
    id: 54,
    image: "/assets/images/fine-tuner.png",
    title: "FINE TUNER",
    link: "https://www.learnitive.com/",
    description: "Build Your Own AI Agents - No Coding Required! ",
    type: "freemium",
    category: "All In One",
  },
  {
    id: 55,
    image: "/assets/images/onetone.jpeg",
    title: "ONETONE",
    link: "https://www.learnitive.com/",
    description: "to make informed decisions ",
    type: "freemium",
    category: "All In One",
  },
];
